
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: formation
    password: formation
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql: true
    defer-datasource-initialization: true




server:
  port: 8081
